/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p_tienda;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import pck_modelo.ProductoDB;

/**
 *
 * @author alex-isgi
 */
public class Catalogo_frm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Catalogo_frm.class.getName());
    private final ProductoDB PRODUCTO;

    public Catalogo_frm() {
        initComponents();
        this.setLocationRelativeTo(null);
        PRODUCTO = new ProductoDB();
        this.construirTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng_category = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ct_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmb_brand = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ct_description = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ct_content = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ct_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cb_status = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        rb_abarrotes = new javax.swing.JRadioButton();
        rb_higiene = new javax.swing.JRadioButton();
        rb_frutas_verduras = new javax.swing.JRadioButton();
        rb_vinos_licores = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jdc_prodDate = new com.toedter.calendar.JDateChooser();
        jdc_expDate = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        cb_criterio = new javax.swing.JComboBox<>();
        ct_parametro = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_refrescar = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_products = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catálogo de productos");
        setAutoRequestFocus(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catálogo de productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        jLabel1.setText("ID del Producto:");

        jLabel2.setText("Marca");

        cmb_brand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ariel", "Bimbo", "Tía Rosa", "Tío Nacho", "Fud", "Aurrera", "Rancho Viejo", "Great Value", "Coca Cola", "Sabritas", "Sin Marca" }));

        jLabel3.setText("Descripción:");

        ct_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_descriptionActionPerformed(evt);
            }
        });

        jLabel4.setText("Contenido:");

        ct_content.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_contentActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio:");

        ct_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_priceActionPerformed(evt);
            }
        });

        jLabel6.setText("Estado:");

        cb_status.setText("Activo");
        cb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_statusActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoría", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        btng_category.add(rb_abarrotes);
        rb_abarrotes.setText("Abarrotes");
        rb_abarrotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_abarrotesActionPerformed(evt);
            }
        });

        btng_category.add(rb_higiene);
        rb_higiene.setText("Higiene Personal");

        btng_category.add(rb_frutas_verduras);
        rb_frutas_verduras.setText("Frutas y Verduras");

        btng_category.add(rb_vinos_licores);
        rb_vinos_licores.setText("Vinos y Licores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb_abarrotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(rb_higiene)
                .addGap(40, 40, 40)
                .addComponent(rb_frutas_verduras)
                .addGap(40, 40, 40)
                .addComponent(rb_vinos_licores)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_abarrotes)
                    .addComponent(rb_higiene)
                    .addComponent(rb_frutas_verduras)
                    .addComponent(rb_vinos_licores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Fecha de elaboración:");

        jLabel8.setText("Fecha de caducidad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36)
                                .addComponent(cmb_brand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(ct_id, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ct_content, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(ct_price))
                            .addComponent(ct_description)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cb_status))
                            .addComponent(jLabel7)
                            .addComponent(jdc_prodDate, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jdc_expDate, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ct_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ct_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ct_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ct_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cb_status))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdc_prodDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdc_expDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        cb_criterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Descripción" }));
        cb_criterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_criterioActionPerformed(evt);
            }
        });

        ct_parametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_parametroActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_refrescar.setText("Refrescar");
        btn_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_criterio, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ct_parametro)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar)
                .addGap(18, 18, 18)
                .addComponent(btn_refrescar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_criterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_parametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_refrescar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        btn_add.setText("Agregar");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setText("Actualizar");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("Eliminar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        jt_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jt_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_productsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_products);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btn_add)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete)
                        .addGap(82, 82, 82)
                        .addComponent(btn_consultar)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ct_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_descriptionActionPerformed

    private void ct_contentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_contentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_contentActionPerformed

    private void ct_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_priceActionPerformed

    private void cb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_statusActionPerformed

    private void rb_abarrotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_abarrotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_abarrotesActionPerformed

    private void ct_parametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_parametroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_parametroActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        this.agregar_actualizar(true);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int fila = jt_products.getSelectedRow();
        int res;
        boolean isBorrado;
        if (fila != -1) {
            res = JOptionPane.showConfirmDialog(this, "¿De verdad desea eliminar el producto: '" + jt_products.getValueAt(fila, 2).toString() + "'? esto no se podrá revertir\n",
                    "Confirmación", JOptionPane.YES_NO_OPTION);
            if (res == JOptionPane.YES_OPTION) {
                isBorrado = PRODUCTO.eliminarProducto(Integer.parseInt(jt_products.getValueAt(fila, 0).toString()));
                this.construirTabla();
                if (!isBorrado) {
                    JOptionPane.showMessageDialog(this, "Algo ha pasado al intentar borrar...");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe de seleccionar un elemento de la tabla...");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        Consulta_frm frm = new Consulta_frm();
        frm.setVisible(true);

    }//GEN-LAST:event_btn_consultarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.limpiar();
    }//GEN-LAST:event_formWindowOpened

    private void cb_criterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_criterioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_criterioActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if (cb_criterio.getSelectedIndex() == 0) {
            try {
                int bus = Integer.parseInt(ct_parametro.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Al momento de hacer una búsqueda por ID asegúrese que el tipo de dato sea numérico");
                return;
            }
            jt_products.setModel(PRODUCTO.buscarProducto(cb_criterio.getSelectedIndex(), ct_parametro.getText()));
        } else {
            jt_products.setModel(PRODUCTO.buscarProducto(cb_criterio.getSelectedIndex(), ct_parametro.getText()));

        }

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        this.agregar_actualizar(false);
    }//GEN-LAST:event_btn_updateActionPerformed

    private void jt_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_productsMouseClicked

        int fila = jt_products.getSelectedRow();

        ct_id.setText(jt_products.getValueAt(fila, 0).toString());
        ct_description.setText(jt_products.getValueAt(fila, 1).toString());
        cmb_brand.setSelectedItem(jt_products.getValueAt(fila, 2).toString());
        ct_content.setText(jt_products.getValueAt(fila, 3).toString());
        ct_price.setText(jt_products.getValueAt(fila, 5).toString());

        if (jt_products.getValueAt(fila, 4).toString().equals("Abarrotes")) {
            rb_abarrotes.setSelected(true);
        } else if (jt_products.getValueAt(fila, 4).toString().equals("Higiene Personal")) {
            rb_higiene.setSelected(true);
        } else if (jt_products.getValueAt(fila, 4).toString().equals("Frutas y Verduras")) {
            rb_frutas_verduras.setSelected(true);
        } else {
            rb_vinos_licores.setSelected(true);
        }

        if (jt_products.getValueAt(fila, 6).toString().equals("true")) {
            cb_status.setSelected(true);
        } else {
            cb_status.setSelected(false);
        }

        String fecha1 = jt_products.getValueAt(fila, 7).toString();
        Date date1;
        try {
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse(fecha1);
            jdc_prodDate.setDate(date1);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error al convertir fecha");
        }

        if (jt_products.getValueAt(fila, 8) != null) {
            String fecha2 = jt_products.getValueAt(fila, 8).toString();
            Date date2;
            try {
                date2 = new SimpleDateFormat("yyyy-MM-dd").parse(fecha2);
                jdc_expDate.setDate(date2);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Error al convertir fecha");
            }
        } else {
            jdc_expDate.setDate(null);
        }

    }//GEN-LAST:event_jt_productsMouseClicked

    private void btn_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refrescarActionPerformed
        this.construirTabla();
    }//GEN-LAST:event_btn_refrescarActionPerformed

    private void limpiar() {
        this.ct_id.setText("");
        this.ct_description.setText("");
        this.ct_content.setText("");
        this.ct_price.setText("");
        this.cb_status.setSelected(false);
        this.cmb_brand.setSelectedIndex(-1);
//        this.btng_category.clearSelection();
        this.rb_abarrotes.setSelected(true);
        this.jdc_expDate.setDate(null);
        this.jdc_prodDate.setDate(null);
        this.ct_id.setEditable(true);
    }

    private void agregar_actualizar(boolean agregar) {

        int id = 0, res = 0;
        String desc, marca = null, categoria = null, cont, dec;
        float precio = 0.0f;
        boolean estado, valido = true, val;

        try {
            id = Integer.parseInt(ct_id.getText());
            if (id < 1) {
                JOptionPane.showMessageDialog(this, "El ID debe de ser mayor a 0");
                valido = false;
                ct_id.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe debe de ser numérico");
            valido = false;
            ct_id.requestFocus();
        }

        desc = ct_description.getText();
        cont = ct_content.getText();

        try {
            marca = cmb_brand.getSelectedItem().toString();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "La descripcion no puede estar vacía");
            valido = false;
            cmb_brand.requestFocus();
        }
        if (desc.isEmpty() || desc.isBlank()) {
            JOptionPane.showMessageDialog(this, "La descripcion no puede estar vacía");
            valido = false;
            ct_description.requestFocus();
        }

        if (cont.isEmpty() || cont.isBlank()) {
            JOptionPane.showMessageDialog(this, "El contenido no puede estar vacío");
            valido = false;
            ct_content.requestFocus();
        }

        try {
            precio = Float.parseFloat(ct_price.getText());
            if (precio < 0) {
                JOptionPane.showMessageDialog(this, "El precio no puede ser negativo");
                valido = false;
                ct_price.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe de ser numérico");
            valido = false;
            ct_price.requestFocus();
        }

        if (cb_status.isSelected()) {
            estado = true;
        } else {
            estado = false;
        }

        if (rb_abarrotes.isSelected()) {
            categoria = rb_abarrotes.getText();
        } else if (rb_higiene.isSelected()) {
            categoria = rb_higiene.getText();
        } else if (rb_frutas_verduras.isSelected()) {
            categoria = rb_frutas_verduras.getText();
        } else if (rb_vinos_licores.isSelected()) {
            categoria = rb_vinos_licores.getText();
        }

        LocalDate now = LocalDate.now();
        java.sql.Date fechaE = null;
        java.sql.Date fechaC = null;
        Date fE = jdc_prodDate.getDate();

        // --- Validación de Fecha de Elaboración ---
        if (fE != null) {
            // java.util.Date a LocalDate para una comparar
            LocalDate prodDate = fE.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            // Se verifica si la fecha de elaboración es futura
            if (prodDate.isAfter(now)) {
                valido = false;
                JOptionPane.showMessageDialog(this, "Ingrese una fecha correcta. La fecha de elaboración no puede ser futura.");
                jdc_prodDate.requestFocus();
                return;
            }

            // Si la fecha es válida, la asignamos
            long dE = fE.getTime();
            fechaE = new java.sql.Date(dE);

        } else {

            JOptionPane.showMessageDialog(this, "La fecha de elaboración es un dato requerido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            valido = false;
            jdc_prodDate.requestFocus();
            return;
        }

        // --- Validación de Fecha de Caducidad ---
        Date fC = jdc_expDate.getDate();

        if (fC != null) {
            // Convertimos ambas fechas a LocalDate para comparar
            LocalDate expDate = fC.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            LocalDate prodDate = fechaE.toLocalDate();

            //Verifica que la fecha de caducidad NO sea ANTERIOR a la de elaboración
            if (expDate.isBefore(prodDate)) {
                valido = false;
                JOptionPane.showMessageDialog(this, "La fecha de elaboracion no debe de exceder la fecha de caducidad");
                jdc_expDate.requestFocus();
                return;
            }

            long dC = fC.getTime();
            fechaC = new java.sql.Date(dC);
        }

        if (agregar && valido) {
            res = PRODUCTO.insertarProducto(id, desc, marca, cont, categoria, precio, estado, fechaE, fechaC);
        }

        if (!agregar && valido) {
            res = PRODUCTO.actualizarProducto(id, desc, marca, cont, categoria, precio, estado, fechaE, fechaC);

        }

        if (res > 0) {
            this.limpiar();
            this.construirTabla();
        }

    }

    private void construirTabla() {
        jt_products.setModel(PRODUCTO.getDatos());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Catalogo_frm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_refrescar;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup btng_category;
    private javax.swing.JComboBox<String> cb_criterio;
    private javax.swing.JCheckBox cb_status;
    private javax.swing.JComboBox<String> cmb_brand;
    private javax.swing.JTextField ct_content;
    private javax.swing.JTextField ct_description;
    private javax.swing.JTextField ct_id;
    private javax.swing.JTextField ct_parametro;
    private javax.swing.JTextField ct_price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdc_expDate;
    private com.toedter.calendar.JDateChooser jdc_prodDate;
    private javax.swing.JTable jt_products;
    private javax.swing.JRadioButton rb_abarrotes;
    private javax.swing.JRadioButton rb_frutas_verduras;
    private javax.swing.JRadioButton rb_higiene;
    private javax.swing.JRadioButton rb_vinos_licores;
    // End of variables declaration//GEN-END:variables
}
